### ISSUE TITLE
[Question] What criteria did you use to choose the LLM TinyLlama-1.1B-Chat-v1.0.Q5_K_M?

### ISSUE THREAD

**Issue by simkimsia** [nickbild/local_llm_assistant#1]
I'm trying to learn from your example here. There must be tons of LLM on huggingface. And yet you picked `TinyLlama-1.1B-Chat-v1.0.Q5_K_M`. What criteria do you use to evaluate for the suitable LLM to use in a Pi?

**Comment by nickbild** [comment]
I was using llamafiles for simplicity, and that would be the only suitable and readily-available option for a Pi in terms of speed. If you are looking beyond llamafiles, maybe try the Huggingface LLM leaderboard: https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard
